TSGL: tsgl::CartesianCanvas Class Reference
tsgl::CartesianCanvas Class Reference
Canvas extended with Cartesian drawing operations.
#include <CartesianCanvas.h>
Public Member Functions
CartesianCanvas (double timerLength=0.0)
Default CartesianCanvas constructor method.
CartesianCanvas (int x, int y, int width, int height, Decimal xMin, Decimal yMin, Decimal xMax, Decimal yMax, std::string t, double timerLength=0.0)
Explicit CartesianCanvas constructor method.
void drawAxes (Decimal originX, Decimal originY, Decimal spacingX, Decimal spacingY)
Draws axes on the Cartesian Canvas.
void drawCircle (Decimal x, Decimal y, Decimal radius, int sides, ColorFloat color=BLACK, bool filled=true)
Draws a circle.
void drawConcavePolygon (int size, Decimal xverts[], Decimal yverts[], ColorFloat color[], bool filled=true)
Draws a Concave polygon with colored vertices.
void drawConvexPolygon (int size, Decimal xverts[], Decimal yverts[], ColorFloat color[], bool filled=true)
Draws a convex polygon with colored vertices.
void drawFunction (const Function &function, float sleepTime=0.0f, ColorFloat color=BLACK)
Plots a function on the screen.
void drawFunction (functionPointer &function, float sleepTime=0.0f, ColorFloat color=BLACK)
Plots a function on the screen.
void drawImage (std::string filename, Decimal x, Decimal y, Decimal w, Decimal h, float a=1.0f)
Draws an image.
void drawLine (Decimal x1, Decimal y1, Decimal x2, Decimal y2, ColorFloat color=BLACK)
Draws a line.
void drawPartialFunction (functionPointer &function, Decimal min, Decimal max, float sleepTime=0.0f, ColorFloat color=BLACK)
Plots part of a function on the screen.
void drawPixel (Decimal row, Decimal col, ColorFloat color=BLACK)
Draws a single pixel, specified in row,column format.
void drawPoint (Decimal x, Decimal y, ColorFloat color=BLACK)
Draws a single pixel, specified in x,y format.
void drawRectangle (Decimal x1, Decimal y1, Decimal x2, Decimal y2, ColorFloat color=BLACK, bool filled=true)
Draws a rectangle.
void drawText (std::string text, Decimal x, Decimal y, unsigned size, ColorFloat color=BLACK)
Draw a string of text.
void drawText (std::wstring text, Decimal x, Decimal y, unsigned size, ColorFloat color=BLACK)
Draw a string of text.
void drawTriangle (Decimal x1, Decimal y1, Decimal x2, Decimal y2, Decimal x3, Decimal y3, ColorFloat color=BLACK, bool filled=true)
Draw a triangle.
void drawTriangleStrip (int size, Decimal xverts[], Decimal yverts[], ColorFloat color[], bool filled=true)
Draws an arbitrary triangle strip with colored vertices.
void getCartesianCoordinates (int screenX, int screenY, Decimal &cartX, Decimal &cartY)
Translates Cartesian coordinates into window coordinates.
Decimal getCartHeight ()
Accessor for the CartesianCanvas's Cartesian height.
Decimal getCartWidth ()
Accessor for the CartesianCanvas's Cartesian width.
Decimal getMaxX ()
Accessor for the CartesianCanvas's right bound.
Decimal getMaxY ()
Accessor for the CartesianCanvas's top bound.
Decimal getMinX ()
Accessor for the CartesianCanvas's left bound.
Decimal getMinY ()
Accessor for the CartesianCanvas's bottom bound.
Decimal getPixelWidth ()
Accessor for the CartesianCanvas's effective pixel width.
Decimal getPixelHeight ()
Accessor for the CartesianCanvas's effective pixel height.
void getScreenCoordinates (Decimal cartX, Decimal cartY, int &screenX, int &screenY)
Translates window coordinates into Cartesian coordinates.
void recomputeDimensions (Decimal xMin, Decimal yMin, Decimal xMax, Decimal yMax)
Recomputes the CartesianCanvas's bounds.
void run (void(*myFunction)(CartesianCanvas &))
Start the CartesianCanvas, run a function on it, and wait for the user to close it.
void run (void(*myFunction)(CartesianCanvas &, int), int i)
Overload for run()
void run (void(*myFunction)(CartesianCanvas &, unsigned), unsigned u)
Overload for run()
void run (void(*myFunction)(CartesianCanvas &, int, int), int i1, int i2)
Overload for run()
void run (void(*myFunction)(CartesianCanvas &, unsigned, unsigned), unsigned u1, unsigned u2)
Overload for run()
void run (void(*myFunction)(CartesianCanvas &, std::string), std::string s)
Overload for run()
void run (void(*myFunction)(CartesianCanvas &, int, std::string), int i, std::string s)
Overload for run()
void run (void(*myFunction)(CartesianCanvas &, std::string, int), std::string s, int i)
Overload for run()
void sleep ()
Sleeps the internal drawing timer of a CartesianCanvas object.
void zoom (Decimal x, Decimal y, Decimal scale)
Zoom the CartesianCanvas with a given center.
void zoom (Decimal x1, Decimal y1, Decimal x2, Decimal y2)
Zoom the CartesianCanvas with the given bounding (Cartesian) coordinates.
Static Public Member Functions
static void runTests ()
Runs the Unit tests for CartesianCanvas.
Detailed Description
Canvas extended with Cartesian drawing operations.
CartesianCanvas provides a Canvas with a Cartesian coordinate system for ease of plotting.
Note:
While on a regular Canvas, pixels higher on the screen have a lower y-value, on a CartesianCanvas, pixels higher on the screen have a higher y-value.
Constructor & Destructor Documentation
tsgl::CartesianCanvas::CartesianCanvas (double timerLength = 0.0)
Default CartesianCanvas constructor method.
This is the default constructor for the CartesianCanvas class.
Parameters:
timerLength The minimum number of seconds between draw cycles for the Canvas. A value less than or equal to 0 sets it to automatic.
Returns:
A new CartesianCanvas, stretching from -400 to +400 on the x axis and -300 to +300 on the y axis, in the middle of the screen with no title. The created CartesianCanvas will take up approximately 90% of the monitor's height, and will have a 4:3 aspect ratio.
tsgl::CartesianCanvas::CartesianCanvas (int x, int y, int width, int height, Decimal xMin, Decimal yMin, Decimal xMax, Decimal yMax, std::string t, double timerLength = 0.0)
Explicit CartesianCanvas constructor method.
This is an explicit constructor for the CartesianCanvas class.
Parameters:
x The x position of the CartesianCanvas window.
y The y position of the CartesianCanvas window.
width The x dimension of the CartesianCanvas window.
height The y dimension of the CartesianCanvas window.
xMin The Cartesian coordinates of the CartesianCanvas's left bound.
yMin The Cartesian coordinates of the CartesianCanvas's bottom bound.
xMax The Cartesian coordinates of the CartesianCanvas's right bound.
yMax The Cartesian coordinates of the CartesianCanvas's top bound.
title The title of the window.
timerLength The minimum number of seconds between draw cycles for the Canvas. A value less than or equal to 0 sets it to automatic.
Returns:
A new CartesianCanvas with the specified position, dimensions, scaling, title, and timer length.
Member Function Documentation
void tsgl::CartesianCanvas::drawAxes (Decimal originX, Decimal originY, Decimal spacingX, Decimal spacingY)
Draws axes on the Cartesian Canvas.
This function draws axes (with tick marks) on the CartesianCanvas, centered at the given (Cartesian) coordinates
Parameters:
originX The horizontal location of the y-axis line.
originY The vertical location of the x-axis line.
spacingX The distance between marks on the x-axis.
spacingY The distance between marks on the y-axis.
void tsgl::CartesianCanvas::drawCircle (Decimal x, Decimal y, Decimal radius, int sides, ColorFloat color = BLACK, bool filled = true)
Draws a circle.
This function draws a circle with the given center, radius, resolution (number of sides), color, and fill status.
Parameters:
x The x coordinate of the circle's center.
y The y coordinate of the circle's center.
radius The radius of the circle in pixels.
sides The number of sides to use in the circle.
color The color of the circle (set to BLACK by default).
filled Whether the circle should be filled (set to true by default).
Note:
Identical to Canvas::drawCircle().
void tsgl::CartesianCanvas::drawConcavePolygon (int size, Decimal xverts[], Decimal yverts[], ColorFloat color[], bool filled = true)
Draws a Concave polygon with colored vertices.
This function draws a ConcavePolygon with the given vertex data, specified as the outer perimeter of the polygon.
Parameters:
size The number of vertices in the polygon.
xverts An array of x positions of said vertices.
yverts An array of y positions of said vertices.
color An array of colors for the said vertices.
filled Whether the Concave polygon should be filled in or not (set to true by default).
Warning:
This function is significantly slower than drawConvexPolygon(). It is not recommended that you draw Convex polygons with this function.
Note:
Identical to Canvas::drawConcavePolygon().
See also:
drawConvexPolygon().
void tsgl::CartesianCanvas::drawConvexPolygon (int size, Decimal xverts[], Decimal yverts[], ColorFloat color[], bool filled = true)
Draws a convex polygon with colored vertices.
This function draws a ConvexPolygon with the given vertex data, specified as the outer perimeter of the polygon.
Parameters:
size The number of vertices in the polygon.
xverts An array of the x positions of said vertices.
yverts An array of the y positions of said vertices.
color An array of colors for the said vertices.
filled Whether the ConvexPolygon should be filled in or not (set to true by default).
Note:
The difference between a convex polygon and a concave polygon is that a convex polygon has all interior angles less than 180 degrees (see http://www.mathopenref.com/polygonconvex.html).
Identical to Canvas::drawConvexPolygon().
Referenced by tsgl::IntegralViewer::trapezoidEvaluate().
void tsgl::CartesianCanvas::drawFunction (const Function & function, float sleepTime = 0.0f, ColorFloat color = BLACK)
Plots a function on the screen.
This function receives a TSGL Function instance as a parameter and plots the function on the CartesianCanvas.
Parameters:
function Reference to the Function to plot.
sleepTime Time to sleep between plotting points
color The color of the vertices of the plotted function (set to BLACK by default).
void tsgl::CartesianCanvas::drawFunction (functionPointer & function, float sleepTime = 0.0f, ColorFloat color = BLACK)
Plots a function on the screen.
This function receives a pointer to a function method as a parameter and plots the function on the CartesianCanvas.
Parameters:
function Pointer to the function-drawing method to plot.
sleepTime Time to sleep between plotting points
color The color of the vertices of the plotted function (set to BLACK by default).
Note:
function must receive exactly one Decimal x parameter, and return a Decimal y parameter.
void tsgl::CartesianCanvas::drawImage (std::string filename, Decimal x, Decimal y, Decimal w, Decimal h, float a = 1.0f)
Draws an image.
This function draws an Image with the given coordinates and dimensions.
Parameters:
function The name of the file to load the image from.
x The x coordinate of the Image's left edge.
y The y coordinate of the Image's top edge.
w The width of the Image.
h The height of the Image.
a The alpha with which to draw the Image (set to 1.0f by default).
Note:
Identical to Canvas::drawImage().
void tsgl::CartesianCanvas::drawLine (Decimal x1, Decimal y1, Decimal x2, Decimal y2, ColorFloat color = BLACK)
Draws a line.
This function draws a Line at the given coordinates with the given color.
Parameters:
x1 The x position of the start of the line.
y1 The y position of the start of the line.
x2 The x position of the end of the line.
y2 The y position of the end of the line.
color The color of the line (set to BLACK by default).
Note:
Identical to Canvas::drawLine().
Referenced by drawAxes(), drawFunction(), and drawPartialFunction().
void tsgl::CartesianCanvas::drawPartialFunction (functionPointer & function, Decimal min, Decimal max, float sleepTime = 0.0f, ColorFloat color = BLACK)
Plots part of a function on the screen.
This function receives a pointer to a function method as a parameter and plots the function on the CartesianCanvas between the specified minimum and maximum coordinates.
Parameters:
function Pointer to the function-drawing method to plot.
min Minimum x value to evaluate and plot
max Maximum x value to evaluate and plot
sleepTime Time to sleep between plotting points
color The color of the vertices of the plotted function (set to BLACK by default).
Note:
function must receive exactly one Decimal x parameter, and return a Decimal y parameter.
Referenced by drawFunction().
void tsgl::CartesianCanvas::drawPixel (Decimal row, Decimal col, ColorFloat color = BLACK)
Draws a single pixel, specified in row,column format.
This function draws a pixel at the given screen coordinates with the given color.
Note:
(0,0) signifies the top-left of the screen when working with a Canvas object.
(0,0) signifies the bottom-left of the screen when working with a CartesianCanvas object.
Parameters:
row The row (y-position) of the pixel.
col The column (x-position) of the pixel.
color The color of the point (set to BLACK by default).
See also:
drawPixel()
Note:
Identical to Canvas::drawPixel().
void tsgl::CartesianCanvas::drawPoint (Decimal x, Decimal y, ColorFloat color = BLACK)
Draws a single pixel, specified in x,y format.
This function draws a pixel at the given Cartesian coordinates with the given color.
Note:
(0,0) signifies the left-top of the screen when working with a Canvas object.
(0,0) signifies the left-bottom of the screen when working with a CartesianCanvas object.
Parameters:
x The x position of the point.
y The y position of the point.
color The color of the point (set to BLACK by default).
See also:
drawPoint()
Note:
Identical to Canvas::drawPoint().
Referenced by drawPixel().
void tsgl::CartesianCanvas::drawRectangle (Decimal x1, Decimal y1, Decimal x2, Decimal y2, ColorFloat color = BLACK, bool filled = true)
Draws a rectangle.
This function draws a Rectangle with the given coordinates, dimensions, and color.
Parameters:
x1 The x coordinate of the Rectangle's left edge.
y1 The y coordinate of the Rectangle's top edge.
x2 The x coordinate of the Rectangle's right edge.
y2 The y coordinate of the Rectangle's bottom edge.
color The color of the rectangle (set to BLACK by default).
filled Whether the rectangle should be filled (set to true by default).
Note:
Identical to Canvas::drawRectangle().
Referenced by tsgl::IntegralViewer::rectangleEvaluate().
void tsgl::CartesianCanvas::drawText (std::string text, Decimal x, Decimal y, unsigned size, ColorFloat color = BLACK)
Draw a string of text.
This function draws a given string of Text at the given coordinates with the given color. The string to draw.
Parameters:
x The x coordinate of the text's left bound.
y The y coordinate of the text's left bound.
size The size of the text in pixels.
color The color of the Text (set to BLACK by default).
Note:
Identical to Canvas::drawText(std::string,..).
Referenced by drawText().
void tsgl::CartesianCanvas::drawText (std::wstring text, Decimal x, Decimal y, unsigned size, ColorFloat color = BLACK)
Draw a string of text.
This function draws a given string of Text at the given coordinates with the given color.
Parameters:
text The UTF8-encoded string to draw.
x The x coordinate of the text's left bound.
y The y coordinate of the text's left bound.
size The size of the text in pixels.
color The color of the Text (set to BLACK by default).
Note:
Identical to Canvas::drawText(std::wstring,..).
void tsgl::CartesianCanvas::drawTriangle (Decimal x1, Decimal y1, Decimal x2, Decimal y2, Decimal x3, Decimal y3, ColorFloat color = BLACK, bool filled = true)
Draw a triangle.
This function draws a Triangle with the given vertices.
Parameters:
x1 The x coordinate of the first vertex of the Triangle.
y1 The y coordinate of the first vertex of the Triangle.
x2 The x coordinate of the second vertex of the Triangle.
y2 The y coordinate of the second vertex of the Triangle.
x3 The x coordinate of the third vertex of the Triangle.
y3 The y coordinate of the third vertex of the Triangle.
color The color of the Triangle (set to BLACK by default).
filled Whether the Triangle should be filled (set to true by default).
Note:
Identical to Canvas::drawTriangle().
void tsgl::CartesianCanvas::drawTriangleStrip (int size, Decimal xverts[], Decimal yverts[], ColorFloat color[], bool filled = true)
Draws an arbitrary triangle strip with colored vertices.
This function draws a TriangleStrip with the given vertex data, specified as a triangle strip.
Parameters:
size The number of vertices in the polygon.
xverts An array of x positions of the vertices.
yverts An array of y positions of the vertices.
color An array of colors for the vertices.
filled Whether the triangle strip should be filled (true) or not (false) (set to true by default).
Note:
Identical to Canvas::drawTriangleStrip().
void tsgl::CartesianCanvas::getCartesianCoordinates (int screenX, int screenY, Decimal & cartX, Decimal & cartY)
Translates Cartesian coordinates into window coordinates.
getCartesianCoordinates() takes a pair of on-screen coordinates and translates them to Cartesian coordinates.
Parameters:
screenX The window's x coordinate.
screenY The window's y coordinate.
cartX A reference variable to be filled with screenX's Cartesian position.
cartY A reference variable to be filled with screenY's Cartesian position.
Decimal tsgl::CartesianCanvas::getCartHeight ()
Accessor for the CartesianCanvas's Cartesian height.
Returns:
The Cartesian height of the CartesianCanvas.
Decimal tsgl::CartesianCanvas::getCartWidth ()
Accessor for the CartesianCanvas's Cartesian width.
Returns:
The Cartesian width of the CartesianCanvas.
Decimal tsgl::CartesianCanvas::getMaxX ()
Accessor for the CartesianCanvas's right bound.
Returns:
The real number corresponding the right of the CartesianCanvas.
Decimal tsgl::CartesianCanvas::getMaxY ()
Accessor for the CartesianCanvas's top bound.
Returns:
The real number corresponding the top of the CartesianCanvas.
Decimal tsgl::CartesianCanvas::getMinX ()
Accessor for the CartesianCanvas's left bound.
Returns:
The real number corresponding the left of the CartesianCanvas.
Decimal tsgl::CartesianCanvas::getMinY ()
Accessor for the CartesianCanvas's bottom bound.
Returns:
The real number corresponding the bottom of the CartesianCanvas.
Decimal tsgl::CartesianCanvas::getPixelHeight ()
Accessor for the CartesianCanvas's effective pixel height.
Returns:
The height corresponding to a single pixel in the current CartesianCanvas.
Decimal tsgl::CartesianCanvas::getPixelWidth ()
Accessor for the CartesianCanvas's effective pixel width.
Returns:
The width corresponding to a single pixel in the current CartesianCanvas.
void tsgl::CartesianCanvas::getScreenCoordinates (Decimal cartX, Decimal cartY, int & screenX, int & screenY)
Translates window coordinates into Cartesian coordinates.
getScreenCoordinates() takes a pair of Cartesian coordinates and translates them to on-screen coordinates.
Parameters:
cartX The Cartesian x coordinate.
cartY The Cartesian y coordinate.
screenX A reference variable to be filled with cartX's window position.
screenY A reference variable to be filled with cartY's window position.
Referenced by drawCircle(), drawConcavePolygon(), drawConvexPolygon(), drawFunction(), drawImage(), drawLine(), drawPartialFunction(), drawPoint(), drawRectangle(), drawText(), drawTriangle(), and drawTriangleStrip().
void tsgl::CartesianCanvas::recomputeDimensions (Decimal xMin, Decimal yMin, Decimal xMax, Decimal yMax)
Recomputes the CartesianCanvas's bounds.
This function recomputes the size variables of CartesianCanvas according to new bounds.
Parameters:
xMin A real number corresponding to the new left edge of the CartesianCanvas.
YMin A real number corresponding to the new bottom edge of the CartesianCanvas.
xMax A real number corresponding to the new right edge of the CartesianCanvas.
xMax A real number corresponding to the new top edge of the CartesianCanvas.
Referenced by CartesianCanvas(), and zoom().
void tsgl::CartesianCanvas::run (void(*)(CartesianCanvas &) myFunction)
Start the CartesianCanvas, run a function on it, and wait for the user to close it.
This function binds another function to the current CartesianCanvas, waits until that function is complete, and waits for the user to close the CartesianCanvas. This function effectively calls start(), myFunction(), and wait() in sequence.
Parameters:
myFunction The function to run on the CartesianCanvas. Must take exactly one parameter of type CartesianCanvas&, which is a reference to the CartesianCanvas to render to.
void tsgl::CartesianCanvas::run (void(*)(CartesianCanvas &, int) myFunction, int i)
Overload for run()
Parameters:
myFunction The function to run on the CartesianCanvas. Must take exactly one parameter of type CartesianCanvas&, which is a reference to the CartesianCanvas to render to.
i An integer argument to myFunction
void tsgl::CartesianCanvas::run (void(*)(CartesianCanvas &, unsigned) myFunction, unsigned u)
Overload for run()
Parameters:
myFunction The function to run on the CartesianCanvas. Must take exactly one parameter of type CartesianCanvas&, which is a reference to the CartesianCanvas to render to.
u An unsigned integer argument to myFunction
void tsgl::CartesianCanvas::run (void(*)(CartesianCanvas &, int, int) myFunction, int i1, int i2)
Overload for run()
Parameters:
myFunction The function to run on the CartesianCanvas. Must take exactly one parameter of type CartesianCanvas&, which is a reference to the CartesianCanvas to render to.
i1 An integer argument to myFunction
i2 An integer argument to myFunction
void tsgl::CartesianCanvas::run (void(*)(CartesianCanvas &, unsigned, unsigned) myFunction, unsigned u1, unsigned u2)
Overload for run()
Parameters:
myFunction The function to run on the CartesianCanvas. Must take exactly one parameter of type CartesianCanvas&, which is a reference to the CartesianCanvas to render to.
u1 An unsigned integer argument to myFunction
u2 An unsigned integer argument to myFunction
void tsgl::CartesianCanvas::run (void(*)(CartesianCanvas &, std::string) myFunction, std::string s)
Overload for run()
Parameters:
myFunction The function to run on the CartesianCanvas. Must take exactly one parameter of type CartesianCanvas&, which is a reference to the CartesianCanvas to render to.
s A string argument to myFunction
void tsgl::CartesianCanvas::run (void(*)(CartesianCanvas &, int, std::string) myFunction, int i, std::string s)
Overload for run()
Parameters:
myFunction The function to run on the CartesianCanvas. Must take exactly one parameter of type CartesianCanvas&, which is a reference to the CartesianCanvas to render to.
i An integer argument to myFunction
s A string argument to myFunction
void tsgl::CartesianCanvas::run (void(*)(CartesianCanvas &, std::string, int) myFunction, std::string s, int i)
Overload for run()
Parameters:
myFunction The function to run on the CartesianCanvas. Must take exactly one parameter of type CartesianCanvas&, which is a reference to the CartesianCanvas to render to.
s A string argument to myFunction
i An integer argument to myFunction
void tsgl::CartesianCanvas::sleep ()
Sleeps the internal drawing timer of a CartesianCanvas object.
A timer is put to sleep until a subsequent event is ready to occur.
The drawing timer is put to sleep until the next drawing frame is ready to occur.
Note:
Identical to Canvas::sleep().
Reimplemented from tsgl::Canvas.
Referenced by tsgl::IntegralViewer::rectangleEvaluate(), and tsgl::IntegralViewer::trapezoidEvaluate().
void tsgl::CartesianCanvas::zoom (Decimal x, Decimal y, Decimal scale)
Zoom the CartesianCanvas with a given center.
This function will re-center the CartesianCanvas at the given coordinates, then zoom with respect to the given scale.
Parameters:
x The coordinate to re-center the screen on.
y The coordinate to re-center the screen on.
scale The zoom scale compared to the original. Less than 1 zooms in, greater than 1 zooms out.
Note:
This function will automatically maintain the current aspect ratio.
Referenced by zoom().
void tsgl::CartesianCanvas::zoom (Decimal x1, Decimal y1, Decimal x2, Decimal y2)
Zoom the CartesianCanvas with the given bounding (Cartesian) coordinates.
This function will zoom the CartesianCanvas with respect to the given bounding coordinates.
Parameters:
x1 The left Cartesian bound.
y1 The bottom Cartesian bound.
x2 The right Cartesian bound.
y2 The top Cartesian bound.
Note:
Setting the right bound lower than the left bound or the top lower than the bottom will just swap the variables.
Warning:
This function will *NOT* automatically maintain the previous aspect ratio.
Change the aspect ratio on-the-fly only with caution.
The documentation for this class was generated from the following files:
CartesianCanvas.h
CartesianCanvas.cpp