TSGL: tsgl::ProgressBar Class Reference
tsgl::ProgressBar Class Reference
Draws and updates a progress bar.
#include <ProgressBar.h>
Public Member Functions
ProgressBar (int x, int y, int width, int height, float minValue, float maxValue, unsigned numSegments)
Explicit ProgressBar constructor method.
~ProgressBar ()
ProgressBar destructor method.
void update (float newValue, int segnum=-1)
Updates a ProgressBar segment with a new value.
Polyline * getBorder (int index)
Accessor for the ProgressBar's representative Polyline array.
Rectangle * getRect (int index)
Accessor for the ProgressBar's representative Rectangle array.
int getSegs ()
Accessor for the ProgressBar's number of segments.
int getSegX (int i)
Accessor for a segment's x position.
int getSegY ()
Accessor for a segment's y position.
Detailed Description
Draws and updates a progress bar.
ProgressBar is a class for holding vertex data for multiple rectangles forming a progress bar. ProgressBar is formed of multiple segments, each of which is thread-safe and updated individually with the update() method. A ProgressBar can be drawn to the screen using Canvas::drawProgress().
Constructor & Destructor Documentation
tsgl::ProgressBar::ProgressBar (int x, int y, int width, int height, float minValue, float maxValue, unsigned numSegments)
Explicit ProgressBar constructor method.
This is the explicit constructor for the ProgressBar class.
Parameters:
x The x position of the left edge of the ProgressBar.
y The y position of the top edge of the ProgressBar.
width The maximum width in pixels of the ProgressBar.
height The maximum height in pixels of the ProgressBar.
minValue The minimum value represented by the ProgressBar.
maxValue The maximum value represented by the ProgressBar.
numSegments The number of segments in the progress bar
Returns:
A new ProgressBar with the specified coordinates, maximum dimensions, value range, and segments.
tsgl::ProgressBar::~ProgressBar ()
ProgressBar destructor method.
This is the destructor for the ProgressBar class.
Frees up memory that was allocated to a ProgressBar instance.
Member Function Documentation
Polyline * tsgl::ProgressBar::getBorder (int index)
Accessor for the ProgressBar's representative Polyline array.
Parameters:
index Index of the segment to access.
Returns:
A pointer to the Polyline array representing segment border i of the ProgressBar.
Referenced by tsgl::Canvas::drawProgress().
Rectangle * tsgl::ProgressBar::getRect (int index)
Accessor for the ProgressBar's representative Rectangle array.
Parameters:
index Index of the segment to access.
Returns:
A pointer to the Rectangle array representing segment i of the ProgressBar.
Referenced by tsgl::Canvas::drawProgress().
int tsgl::ProgressBar::getSegs () [inline]
Accessor for the ProgressBar's number of segments.
Returns:
The number of segments in the ProgressBar.
Referenced by tsgl::Canvas::drawProgress().
int tsgl::ProgressBar::getSegX (int i) [inline]
Accessor for a segment's x position.
Parameters:
i Index of the segment
Returns:
The x-coordinate of the left edge of segment i in the ProgressBar.
Referenced by tsgl::Canvas::drawProgress().
int tsgl::ProgressBar::getSegY () [inline]
Accessor for a segment's y position.
Returns:
The y-coordinate of the top edge of the ProgressBar.
Referenced by tsgl::Canvas::drawProgress().
void tsgl::ProgressBar::update (float newValue, int segnum = -1)
Updates a ProgressBar segment with a new value.
This function updates the segment seg of the ProgressBar to represent the new value newV. If newV is less than the segment's minimum value, the segment is set to its minimum value. If newV is more than the segment's maximum value, the segment is set to its maximum value.
Parameters:
newValue The value to set the segment to.
segnum The segment whose value to update. A value of -1 indicates the current thread number.
Note:
The minimum value for a segment is calculated as minV + (maxV-minV)*seg/segs
The maximum value for a segment is calculated as minV + (maxV-minV)*(seg+1)/segs
The documentation for this class was generated from the following files:
ProgressBar.h
ProgressBar.cpp